package se.consid.codesample;

import java.util.List;

public class EmployeeService {
    public List<Employee> getEmployees() {
        return List.of(
            new Employee("Kenneth", "Morrison"),
            new Employee("Ronald", "Fuller"),
            new Employee("Lucas", "Greer"),
            new Employee("Barbara", "Strickland"),
            new Employee("Sarah", "Stewart"),
            new Employee("Ruben", "Ibarra"),
            new Employee("Alex", "Arroyo"),
            new Employee("Elisabeth", "Meadows"),
            new Employee("Mason", "Mooney"),
            new Employee("Stuart", "Cotton"),
            new Employee("Bonnie", "Schultz"),
            new Employee("Marilyn", "Baxter"),
            new Employee("Briony", "Johnston"),
            new Employee("Elisha", "Decker"),
            new Employee("Rory", "Martinez"),
            new Employee("Aaron", "Kelley"),
            new Employee("Anthony", "Winter"),
            new Employee("Maryam", "Butler"),
            new Employee("Tamsin", "Cherry"),
            new Employee("Chloe", "Eaton"),
            new Employee("Rodney", "Callahan"),
            new Employee("Finnian", "Yates"),
            new Employee("John", "York"),
            new Employee("Santiago", "Contreras"),
            new Employee("Kurt", "O'Reilly"),
            new Employee("Tiana", "Waters"),
            new Employee("Kade", "Estes"),
            new Employee("Jenny", "Cobb"),
            new Employee("Dennis", "Rodgers"),
            new Employee("Sophia", "Briggs"),
            new Employee("Doris", "Crosby"),
            new Employee("Hugh", "Spencer"),
            new Employee("Zakaria", "Soto"),
            new Employee("Tessa", "Lester"),
            new Employee("Maia", "Daniel"),
            new Employee("Abbie", "Chandler"),
            new Employee("Tiffany", "Kent"),
            new Employee("Irene", "Melendez"),
            new Employee("Rex", "Cox"),
            new Employee("Leona", "Larsen"),
            new Employee("Syed", "Edwards"),
            new Employee("Samir", "Mcconnell"),
            new Employee("Malik", "Paul"),
            new Employee("Kobe", "Barry"),
            new Employee("Noah", "Alexander"),
            new Employee("Veronica", "O'Quinn"),
            new Employee("Juliet", "Fitzgerald"),
            new Employee("Alice", "Jensen"),
            new Employee("Gideon", "Barrett"),
            new Employee("Tori", "Davis")
        );
    }
}
